name: Next.js build

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "web/next.js/**"

jobs:
  build-codebase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ./web/next.js/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn
        working-directory: ./web/next.js
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Build frontend
        working-directory: ./web/next.js
        run: yarn build
