name: Build docker image

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image-name:
          - app

    env:
      IMAGE_NAME: ${{ matrix.image-name }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get the latest tag version
        id: get-version
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo $VERSION
          echo ::set-output name=VERSION::$VERSION

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          target: production
          context: ./web/next.js
          build-args: |
            NODE_ENV=production
          tags: |
            ghcr.io/kachar/yadi-app:${{ steps.get-version.outputs.VERSION }}
            ghcr.io/kachar/yadi-app:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
